version: '3'
services:
  ark-server:
    restart: unless-stopped
    build:
      context: .
    image: asa-server
    container_name: asa-server
    environment:
      - SESSION_NAME=Nulltron
      - ADMIN_PASSWORD
      - MAX_PLAYERS=20
      - ShowPlayerOnMAP=True
      - PreventSurvivorDownload=True
      - PreventItemDownload=True
      - PreventDinoDownload=True
      - PreventSurvivorUpload=False
      - PreventItemUpload=False
      - PreventDinoUpload=False
      - QUERY_PORT=${QUERY_PORT:-27015}
      - GAME_PORT=${GAME_PORT:-7777}
      - MODS
      - CMD_ARGS
    ports:
      - "${QUERY_PORT:-27015}:${QUERY_PORT:-27015}/udp"
      - "${GAME_PORT:-7777}:${GAME_PORT:-7777}/udp"
    volumes:
      - "ark-data:/root/.steam/steam/steamapps/common/ARK Survival Ascended Dedicated Server"

volumes:
  ark-data:
    driver: local
    name: ark-data